package models

// Profile public model generated by bindu
type Profile struct {
	FullName    string
	CompanyName string
	Address     string
	Postcode    string
	Phone       string
	UserID      uint64 `gorm:"uniqueIndex;not null"`
	DefaultProperties
}
