package models

// User public model generated by bindu
type User struct {
	Email    string `gorm:"uniqueIndex;not null;size:256"`
	Password string `form:"password" json:"password" binding:"required" json:"-"`
	Role     string
	Verified bool `json:"verified"`
	Hostname string
	Profile  Profile
	DefaultProperties
}

type FrontendUserData struct {
	FullName   string
	Email      string
	Role       string
	Hostname   string
	ButtonText string
	Url        string
}
