package models

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

// Service public model generated by bindu
type Order struct {
	OrderServices    []OrderServices
	PropertyType     string
	Subtotal         float32
	Discount         float32
	Total            float32
	UserId           uint64
	PropertyAddress  string
	PropertyPostCode string
	LandlordName     string
	FullName         string
	Email            string
	Phone            string
	CompanyName      string
	BillingAddress   string
	BillingPostCode  string
	OrderNotes       string
	ID               uint64 `gorm:"primary_key"`
	InvID            uint64
	CreatedAt        *time.Time
	UpdatedAt        *time.Time
	DeletedAt        *time.Time            `sql:"index" json:"-"`
	IsDel            soft_delete.DeletedAt `gorm:"softDelete:flag,DeletedAtField:DeletedAt"`
	OrderStatus      string                // same as woocommerce order status
	PaymentStatus    string
	PaymentMethod    string
	CreatedBy        string
}

// OrderService public model generated by bindu
type OrderServices struct {
	OrderID   uint64 `json:"-"`
	ServiceID int
	Title     string
	Subtotal  float32
	Discount  float32
	Total     float32
	ID        uint64 `gorm:"primary_key"`
	CreatedAt *time.Time
	UpdatedAt *time.Time            `json:"-"`
	DeletedAt *time.Time            `sql:"index" json:"-"`
	IsDel     soft_delete.DeletedAt `gorm:"softDelete:flag,DeletedAtField:DeletedAt"`
	Index     int
}
