package models

// Profile public model generated by bindu
type Profile struct {
	FullName    string
	CompanyName string
	Address     string
	Postcode    string
	Phone       string
	UserID      uint64 `gorm:"unique;not null"`
	DefaultProperties
}

type DashboardReport struct {
	TotalCertificates int

	ExpiringProperty []Property
	TotalProperties  int
	Properties       []Property
	Complaince       int
	TotalOrders      int
	RecentOrders     []Order
}
