package models

import (
	"time"

	"gorm.io/plugin/soft_delete"
)
// all postcodes , longitude and latitude
type Postcode struct {

}
// Service public model generated by bindu
type Service struct {
	ID                int `gorm:"primary_key;auto_increment;not_null" json:"ID"`
	ServiceCategory   ServiceCategory
	Title             string
	Price             float32
	OfferPrice        float32
	CreatedAt         *time.Time
	UpdatedAt         *time.Time
	DeletedAt         *time.Time            `gorm:"index"`
	IsDel             soft_delete.DeletedAt `gorm:"softDelete:flag,DeletedAtField:DeletedAt"`
	Status            bool
	IsSelected        string
	ServiceCategoryID int
	ShortNote         string
	ShortInfo         string
}

// ServiceCategory public model generated by bindu
type ServiceCategory struct {
	Title         string
	ID            int `gorm:"primarykey"`
	CreatedAt     *time.Time
	UpdatedAt     *time.Time
	DeletedAt     *time.Time            `gorm:"index"`
	IsDel         soft_delete.DeletedAt `gorm:"softDelete:flag,DeletedAtField:DeletedAt"`
	Services      []Service
	PropertyTypes []PropertyType
	Checked       string
}

type PropertyType struct {
	DefaultProperties
	Title             string
	ServiceCategoryID int
}
